
import java.awt.GridLayout;
import java.io.File;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.border.EmptyBorder;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author santosh rai
 */
public class Datacarving extends javax.swing.JFrame {

    /**
     * Creates new form Datacarving
     */
    public Datacarving() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        submitButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Carving Tool");
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setSize(new java.awt.Dimension(500, 500));

        jPanel3.setMaximumSize(new java.awt.Dimension(200, 200));
        jPanel3.setPreferredSize(new java.awt.Dimension(154, 10));
        jPanel3.setLayout(new java.awt.GridLayout(2, 2, 0, 2));

        jTextField1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), new java.awt.Color(153, 153, 153)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextField1);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        jTextField2.setMinimumSize(new java.awt.Dimension(6, 21));
        jPanel3.add(jTextField2);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setText("Browse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel2.setAutoscrolls(true);
        jPanel2.setLayout(new java.awt.GridLayout(3, 6));

        jCheckBox1.setText("Image");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox1);

        jCheckBox2.setText(".HTML");
        jPanel2.add(jCheckBox2);

        jCheckBox3.setText(".PDF");
        jPanel2.add(jCheckBox3);

        jCheckBox4.setText(".DOC");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox4);

        jCheckBox5.setText("PPT");
        jPanel2.add(jCheckBox5);

        jCheckBox6.setText(".EXCEL");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox6);

        jCheckBox7.setText("Thumbs.db");
        jPanel2.add(jCheckBox7);

        jCheckBox8.setText(".ZIP");
        jPanel2.add(jCheckBox8);

        jCheckBox9.setText(".BMB");
        jPanel2.add(jCheckBox9);

        jCheckBox10.setText("AVI");
        jPanel2.add(jCheckBox10);

        jCheckBox11.setText(".DAT");
        jCheckBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox11ActionPerformed(evt);
            }
        });
        jPanel2.add(jCheckBox11);

        jCheckBox12.setText(".MP4");
        jPanel2.add(jCheckBox12);

        jCheckBox13.setText(".MOV");
        jPanel2.add(jCheckBox13);

        jCheckBox14.setText(".MP3");
        jPanel2.add(jCheckBox14);

        jCheckBox15.setText("WMV");
        jPanel2.add(jCheckBox15);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(173, 20));
        jPanel1.setLayout(new java.awt.GridLayout(1, 3));

        submitButton.setText("Start");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton);

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        final JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("sdfsd");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        int retVal = chooser.showOpenDialog(this);
        System.out.println(chooser.getSelectedFile());
        File filePath = chooser.getSelectedFile();
        System.out.println(filePath.getName().charAt(0));

        inputFolder = filePath;
        jTextField1.setText(filePath.toString());
//        KMPTest.startCarving(filePath);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        final JFileChooser chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("sdfsd");
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        //
        int retVal = chooser.showOpenDialog(this);
        System.out.println(chooser.getSelectedFile());
        File filePath = chooser.getSelectedFile();
        System.out.println(filePath.getName().charAt(0));
        outputFolder = filePath;
        jTextField2.setText(filePath.toString());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
//        System.out.println("selectdedFileType:"+selectdedFileType+"image".equals(selectdedFileType));
        System.out.println(selectdedFileType + ":" + inputFolder + ":" + outputFolder); 
        if (outputFolder != null) {
            if( jCheckBox1.isSelected())
                KMPTest.startCarving(inputFolder,"image", outputFolder); 
            if( jCheckBox2.isSelected()) 
                KMPTest.startCarving(inputFolder,"html", outputFolder);
            if( jCheckBox3.isSelected())
                KMPTest.startCarving(inputFolder,"pdf", outputFolder);
            if( jCheckBox4.isSelected())
                KMPTest.startCarving(inputFolder,"doc", outputFolder);
            if( jCheckBox5.isSelected())
                KMPTest.startCarving(inputFolder,"ppt", outputFolder);
            if( jCheckBox6.isSelected())
                KMPTest.startCarving(inputFolder,"excel", outputFolder);
            if( jCheckBox7.isSelected())
                KMPTest.startCarving(inputFolder,"thumdb", outputFolder);
            if( jCheckBox8.isSelected())
                KMPTest.startCarving(inputFolder,"zip", outputFolder);
            if( jCheckBox9.isSelected())
                KMPTest.startCarving(inputFolder,"bmb", outputFolder);
            if( jCheckBox10.isSelected())
                KMPTest.startCarving(inputFolder,"avi", outputFolder);
            if( jCheckBox11.isSelected())
                KMPTest.startCarving(inputFolder,"dat", outputFolder);
            if( jCheckBox12.isSelected())
                KMPTest.startCarving(inputFolder,"mp4", outputFolder);
            if( jCheckBox13.isSelected())
                KMPTest.startCarving(inputFolder,"mov", outputFolder);
            if( jCheckBox14.isSelected())
                KMPTest.startCarving(inputFolder,"mp3", outputFolder);
            if( jCheckBox15.isSelected())
                KMPTest.startCarving(inputFolder,"wmv", outputFolder);
           JOptionPane.showMessageDialog(this, "Completed!");
            
            
        } else {
            JOptionPane.showMessageDialog(this, "Please select output directory");
        }
        //System.exit(0);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox11ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private static File[] getAllDrives() {
        File[] drives = File.listRoots();
        if (drives != null && drives.length > 0) {
            for (File aDrive : drives) {
                System.out.println(aDrive);
            }
        }
        return drives;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Datacarving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Datacarving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Datacarving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Datacarving.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Datacarving().setVisible(true);
            }
        });
    }
    private String selectdedFileType;
    private File inputFolder;
    private File outputFolder;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
